### PR TITLE
:%s/nano/vim/g

### PR DESCRIPTION
**Pull request by tim-clifford**
nano is easier to learn, but is it really *worth* learning?

[Copypasta to add credibility to my argument](https://rudism.com/vim-creep/)

### CODE REVIEW

**Comment by edwinbalani** [comment]
Extract from `pip:/etc/profile.d/srcf.sh`:

```sh
export VISUAL="nano"  # I think :q! says it all
export EDITOR="nano"
```

So there is precedent :P

**Comment by tim-clifford** [comment]
@edwinbalani if only I could open a PR into that too...

I think [this banger](https://bugzilla.redhat.com/show_bug.cgi?id=638477#c129) of a quote from Linus Torvalds is applicable here, given that standards and precedent are essentially the same...

> Standards are paper. I use paper to wipe my butt every day. That's how much that paper is worth

**Comment by CHTJonas** [comment]
Okay fine, I'll bite! This PR changes a tutorial, the primary audience of which are people who are usually either mostly or completely unfamiliar with Linux, the command line or both. I think people who already know Vim will know that they can switch out the `nano` commands for `vim` ones and that's fine, of course. But let's not kid ourselves that Vim isn't harder for beginners to use than Nano; making someone learn a non-trivial text editor (even if it only takes 15 minutes) just so they can get a 'Hello, World' Django app running makes things less not more accessible IMO.

That being said, I could see this fitting nicely into a separate tutorial/docs page about text editors with a note in other tutorials that "we've used GNU Nano here but you can use another text editor [hyperlink]".

**Comment by tim-clifford** [comment]
Yeah, I see your point and I think we can do better than this PR as-is. I think in any case the note about nano is a bit misleading and actually fits vim much better than it does nano. How about something like this:

> Note that the last command starts the nano text editor. This is a simple editor which is sufficient for most tasks. If you get stuck in it, pressing control-x will return to the command prompt. If you are looking for a more powerful editor, albeit with a steeper learning curve, you might want to try vim.

Aside from my own personal bias, I do wish someone had recommended vim to me a long time ago. It's easy to forget that **everyone** is unfamiliar with linux at some point, and I think it's worth making people at the very least *aware* of high productivity tools like vim.

A dedicated page about text editors would also be pretty cool.

**Comment by CMTC** [comment]
As we all know, ed(1) is the standard editor. Despite this, I think the tutorial should stay as is. People who don't know cp, rm, mv etc. are probably going to expect a text editor to work more like nano than vim, and the friendly, comforting hints along the bottom of nano are going to help too.

Whether nano is worth learning and whether it is particularly powerful is another thing, which I'm not sure I can comment on.

I never learnt vim; I used emacs for a while, which I found to be a useful experience, and have learnt to get by with ed and vi on systems which don't have other editors. For really powerful editors, which were designed post-mouse and make use of that peripheral in a clever way, see sam and acme on Plan 9 (ports to Unix exist).

**Comment by tim-clifford** [comment]
@CMTC I agree that for new users, nano is more familiar, yeah. I do think that the wording would be better tweaked a bit though.

I used nano for a long time, and then switched to vim and never looked back. I have to say, nano is really not usable beyond the odd config tweak, whereas vim can do absolutely whatever you want if you're willing to put some time in (see my config and the plugins I've written if you don't believe me)

Getting a bit off-topic, but I don't believe adding a mouse *ever* increases productivity in the long run (for a text editor), and that is a hill I'll die on, but perhaps another time.

[Relevant and very accurate copypasta](https://old.reddit.com/r/linuxmasterrace/comments/51t7z6/calling_all_linux_copypastas/d7f347o/). I don't usually have this many...

**Comment by CMTC** [comment]
So it seems the answer may be to just remove the remark about power etc. I think few of us would disagree on that.

@tim-clifford People have argued about mouse and keyboard navigation before. I've heard [people suggest the data back up the opposite of what you say](https://marc.info/?l=9fans&m=111558805207697), but whatever. Ofc, if you're worried about the time it takes to reach the mouse, you can always use a keyboard with a trackpoint (which iirc IBM developed in an attempt to solve this exact problem).

Navigation isn't all you can do with a mouse either; without a mouse, I don't think things like plumbing would be so easy to implement, and these do save time. If you haven't tried it, acme really can be a productive editor, and it's almost certainly easier to extend in clever ways than the likes of vim are; it exposes everything as a filesystem, so you can use any language you like to augment its functionality. Russ Cox has a nice [demo](https://research.swtch.com/acme) which shows this stuff off well. If you want to give it a go, you could do worse than trying it on the srcf's (slightly pre-production) plan 9 instance; contact nine-accounts@ for an account. :-)

**Comment by matiasilva** [comment]
First off, thanks for the contribution. I agree with @CHTJonas here but appreciate the overall intention of the PR which has stirred up some useful discussion. Your insights into wishing that someone had shown you vim early on is useful for us as we try to increasingly help people get comfortable with Linux. I would recommend you either update the PR by instead mentioning vim as a powerful alternative and reword the existing text, or close it and if you're willing write up a tutorial on text editors!

Incidentally, I find it hard to believe that someone would use those exact words to describe nano (powerful, etc), so it's possible, though I may be misremembering, that originally it was vim but when writing that tutorial by adapting an original text file somewhere in the SRCF, I changed it to nano.

**Comment by tim-clifford** [comment]
@CMTC Entirely off topic at this point but I wholeheartedly disagree with the methods used for that data you linked, entirely because no good vim users use the arrow keys, or for that matter, hjkl, very much. There are much faster ways of navigating (half of the keys on the keyboard come to mind).

ACME has some really interesting ideas, but it does look quite a lot slower than vim to me. Another thing that people don't tend to mention is that a lot of the benefits of keyboard usage come down to comfort not speed: when aiming for icons with a mouse, it takes more concentration to get it right, plus you have to move your hand, there's more eye strain following the cursor, etc.

I'll be sure to check out plan 9 at some point.

@matiasilva the reword I suggested in an earlier comment seems to have slipped through the net, I'll turn it into a commit. Re the reword, from vim: I was thinking the same lol

**Comment by matiasilva** [comment]
Looks good! In a few days, the underlying platform behind the docs will change so to avoid creating more merge conflicts I will merge this one after that one. Thanks!

**Review by CHTJonas — APPROVED** [review]
I'm now happy with where this is 🚢

**Comment by matiasilva** [comment]
I've added the PR contents to 9f6b1f48e9251e2b6771f8d14120edab6027c9b3. The file this PR is modifying doesn't even exist anymore! Thanks for the PR.

**Pull request closed without merging**
