### PR TITLE
Redirect old society pages to group pages

### PR DESCRIPTION
**Pull request by dalcde**

### CODE REVIEW

**Comment by matiasilva** [comment]
For how long are you planning on keeping these pages?

**Comment by dalcde** [comment]
Possibly forever, perhaps replace with an actual http redirect later on.

**Comment by matiasilva** [comment]
I admire your adherence to backwards compatibility. Given that these docs have been available for only a brief period of time, I think that it is unnecessary. However, I don't see why they can't be included in the short term for say 1 year. After that, I think they will just be confusing for any contributors to docs.

**Comment by mchesterkadwell** [comment]
That seems like a good plan to me. It's courtesy to help people with an explicit explanation of a big change, but we don't want to have to maintain actual pages for this purpose forever.

**Pull request merged**
